In [36]:
import pandas as pd

dados = {
    'Nome': ['Fábio', 'Maria', 'Carlos', 'Ana', 'Lucas'],
    'Idade': [18, 22, 30, 25, 19],
    'Naturalidade': ['SP', 'AM', 'RJ', 'SP', 'RJ']
}

df=pd.DataFrame(dados)
print(df)

     Nome  Idade Naturalidade
0   Fábio     18           SP
1   Maria     22           AM
2  Carlos     30           RJ
3     Ana     25           SP
4   Lucas     19           RJ

In [37]:
# Verificar Coluna Especifica
print(df['Naturalidade'])

0    SP
1    AM
2    RJ
3    SP
4    RJ
Name: Naturalidade, dtype: str

In [38]:
# Puxar valor com condicional
print(df["Idade"]>20)

0    False
1     True
2     True
3     True
4    False
Name: Idade, dtype: bool

In [39]:
# Puxar Valor Condicional Com Infos Completas
# 1.Filtrar a idade - f["Idade"]>20
# 2.Puxar todas as infos - df[]
print(df[
    df['Idade']>20
])

     Nome  Idade Naturalidade
1   Maria     22           AM
2  Carlos     30           RJ
3     Ana     25           SP

In [40]:
# Puxar Os Registros Do Fábio
# 1.Filtro print(df['Nome']=='Fábio')

print(df[
    df['Nome']=='Fábio'
])

    Nome  Idade Naturalidade
0  Fábio     18           SP

Anotações Prof

In [41]:
# Transposição
# df.T 

print(df)
print(df.T)

     Nome  Idade Naturalidade
0   Fábio     18           SP
1   Maria     22           AM
2  Carlos     30           RJ
3     Ana     25           SP
4   Lucas     19           RJ
                  0      1       2    3      4
Nome          Fábio  Maria  Carlos  Ana  Lucas
Idade            18     22      30   25     19
Naturalidade     SP     AM      RJ   SP     RJ

In [42]:
# Gerar Estatisticas Descritivas

df.describe()

           Idade
count   5.000000
mean   22.800000
std     4.868265
min    18.000000
25%    19.000000
50%    22.000000
75%    25.000000
max    30.000000

In [43]:
# Apresenta as primeiras linhas

df.head(2)

    Nome  Idade Naturalidade
0  Fábio     18           SP
1  Maria     22           AM

In [44]:
# Aplicar Uma Função Para Calcular Idade +2

df['Idade2']=df['Idade'].apply(lambda x : x + 2)
df

     Nome  Idade Naturalidade  Idade2
0   Fábio     18           SP      20
1   Maria     22           AM      24
2  Carlos     30           RJ      32
3     Ana     25           SP      27
4   Lucas     19           RJ      21

In [45]:
# Contagem de Valor
df['Naturalidade'].value_counts()

Naturalidade
SP    2
RJ    2
AM    1
Name: count, dtype: int64

In [47]:
# Ordenar Dados
# ascending = True (Ordem Crescente)
# ascending = False (Ordem Descrescente)
df.sort_values('Naturalidade', ascending=False)

     Nome  Idade Naturalidade  Idade2
0   Fábio     18           SP      20
3     Ana     25           SP      27
2  Carlos     30           RJ      32
4   Lucas     19           RJ      21
1   Maria     22           AM      24

In [48]:
# Agrupar / Calculo de Média de Idade por Naturalidade

media_nat=df.groupby('Naturalidade')['Idade'].mean()

print(media_nat)

Naturalidade
AM    22.0
RJ    24.5
SP    21.5
Name: Idade, dtype: float64